using System.Numerics;
using Content.Client.Imperial.Medieval.CapturePoint.UI.MedievalWindow;
using Content.Client.Imperial.Medieval.UserInterface.Elements;
using Robust.Client.ResourceManagement;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;
using Robust.Shared.Utility;

namespace Content.Client.Imperial.Medieval.UserInterface.Windows;

/// <summary>
///     imperial medieval - campfire cooking window: the fire itself in the middle with the food laid out
///     around it, firewood for the cook time. Talks to the stock microwave logic through
///     <see cref="MedievalCampfireBoundUserInterface"/>.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class MedievalCampfireMenu : MedievalWindow
{
    [Dependency] private readonly IGameTiming _timing = default!;
    [Dependency] private readonly IEntityManager _entMan = default!;
    [Dependency] private readonly IResourceCache _resCache = default!;

    public const int MaxLogs = 6;
    public const uint SecondsPerLog = 5;

    // matches the stock microwave capacity the campfire uses
    private const int PotSlots = 10;

    private static readonly Vector2 PotSize = new(320, 300);
    private static readonly Vector2 RingCenter = new(160, 125);
    private static readonly Vector2 SlotSize = new(44, 44);
    private static readonly Vector2 SlotIconSize = new(32, 32);
    private static readonly Vector2 FireSize = new(96, 96);
    private static readonly Vector2 LogSize = new(40, 40);
    private const float LogGap = 4;
    private const float LogsTop = 252;
    private const float RingRadiusX = 120;
    private const float RingRadiusY = 95;

    private static readonly SpriteSpecifier LogSprite =
        new SpriteSpecifier.Rsi(new ResPath("/Textures/Objects/Specific/Hydroponics/towercap.rsi"), "produce");

    // burning firewood: glowing embers flicker between these, then the log cools down to ash
    private static readonly Color EmberBright = Color.FromHex("#ffc266");
    private static readonly Color EmberDeep = Color.FromHex("#ff6a1a");
    private static readonly Color AshColor = Color.FromHex("#2a2320");
    private const float EmberFlickerSpeed = 9f;

    private static readonly Color TimeSetColor = MedievalUiStyle.Gold;
    private static readonly Color TimeUnsetColor = MedievalUiStyle.TextMuted;

    /// <summary>Picked cook time in seconds, 0 = only warm up.</summary>
    public event Action<uint>? OnCookTimeSelected;

    public event Action<EntityUid>? OnIngredientPressed;

    private readonly SpriteView _fire;
    private readonly List<TextureRect> _slotIcons = new();
    private readonly EntityUid?[] _slotEntities = new EntityUid?[PotSlots];
    private readonly List<CampfireLogButton> _logs = new();

    private bool _busy;
    private bool _empty;
    private TimeSpan _cookStart;
    private TimeSpan _cookEnd;
    private uint _cookSeconds;
    private uint _selectedSeconds;

    public MedievalCampfireMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        PotLayout.SetSize = PotSize;

        ApplyMedievalFonts();

        _fire = new SpriteView
        {
            Scale = new Vector2(3, 3),
            SetSize = FireSize,
            MouseFilter = MouseFilterMode.Ignore,
        };
        Place(_fire, RingCenter - FireSize / 2, FireSize);

        for (var i = 0; i < PotSlots; i++)
        {
            var index = i;
            var icon = new TextureRect
            {
                Stretch = TextureRect.StretchMode.KeepAspectCentered,
                SetSize = SlotIconSize,
                HorizontalAlignment = HAlignment.Center,
                VerticalAlignment = VAlignment.Center,
            };

            // never disabled, so empty slots keep the same look as full ones; clicks are filtered instead
            var slot = new MedievalToggleButton { SetSize = SlotSize };
            slot.AddChild(icon);
            slot.OnPressed += _ =>
            {
                if (!_busy && _slotEntities[index] is { } uid)
                    OnIngredientPressed?.Invoke(uid);
            };

            // lay the slots out in a ring around the fire, starting from the top
            var angle = -MathF.PI / 2 + MathF.Tau * i / PotSlots;
            var pos = RingCenter + new Vector2(MathF.Cos(angle) * RingRadiusX, MathF.Sin(angle) * RingRadiusY) - SlotSize / 2;

            Place(slot, pos, SlotSize);
            _slotIcons.Add(icon);
        }

        // firewood lies in a row under the fire, no frames
        var logTexture = _entMan.System<SpriteSystem>().Frame0(LogSprite);
        var rowWidth = MaxLogs * LogSize.X + (MaxLogs - 1) * LogGap;
        var logX = (PotSize.X - rowWidth) / 2;

        for (var i = 1; i <= MaxLogs; i++)
        {
            var count = i;
            var log = new CampfireLogButton
            {
                TextureNormal = logTexture,
                ToolTip = Loc.GetString("medieval-campfire-menu-seconds", ("time", count * SecondsPerLog)),
            };
            log.OnPressed += _ => OnCookTimeSelected?.Invoke((uint) count * SecondsPerLog);

            Place(log, new Vector2(logX, LogsTop), LogSize);
            logX += LogSize.X + LogGap;
            _logs.Add(log);
        }

        SetCookTime(0);
    }

    private void ApplyMedievalFonts()
    {
        MedievalUiStyle.ApplyTitleFont(this, _resCache);
        MedievalUiStyle.ApplyTextFont(_resCache, TimeLabel, StatusLabel, StartButton, EjectButton);
    }

    // fixed box in the pot layout via margins, so a slot never resizes to whatever icon it holds
    private void Place(Control control, Vector2 position, Vector2 size)
    {
        PotLayout.AddChild(control);
        LayoutContainer.SetMarginLeft(control, position.X);
        LayoutContainer.SetMarginTop(control, position.Y);
        LayoutContainer.SetMarginRight(control, position.X + size.X);
        LayoutContainer.SetMarginBottom(control, position.Y + size.Y);
    }

    public void SetFire(EntityUid campfire)
    {
        _fire.SetEntity(campfire);
    }

    public void SetCookTime(uint seconds)
    {
        _selectedSeconds = seconds;
        var lit = (int) Math.Clamp(seconds / SecondsPerLog, 0, MaxLogs);

        for (var i = 0; i < _logs.Count; i++)
        {
            _logs[i].Lit = i < lit;
        }

        if (lit == 0)
        {
            TimeLabel.Text = Loc.GetString("medieval-campfire-menu-time-none");
            TimeLabel.FontColorOverride = TimeUnsetColor;
            StartButton.ToolTip = Loc.GetString("medieval-campfire-menu-time-warm");
        }
        else
        {
            TimeLabel.Text = Loc.GetString("medieval-campfire-menu-time", ("time", seconds));
            TimeLabel.FontColorOverride = TimeSetColor;
            StartButton.ToolTip = null;
        }
    }

    public void SetContents(IReadOnlyList<(EntityUid Uid, string Name, Texture? Icon)> contents)
    {
        for (var i = 0; i < _slotIcons.Count; i++)
        {
            var icon = _slotIcons[i];
            var slot = (Control) icon.Parent!;

            if (i < contents.Count)
            {
                var (uid, name, texture) = contents[i];
                _slotEntities[i] = uid;
                icon.Texture = texture;
                slot.ToolTip = name;
            }
            else
            {
                _slotEntities[i] = null;
                icon.Texture = null;
                slot.ToolTip = null;
            }
        }
    }

    public void SetBusy(bool busy, bool empty, TimeSpan cookEnd, uint cookSeconds)
    {
        _busy = busy;
        _empty = empty;

        StartButton.Disabled = busy || empty;
        EjectButton.Disabled = busy || empty;

        foreach (var log in _logs)
        {
            log.Disabled = busy;

            // while cooking the burn colours are refreshed every frame; clearing them on every state update would flash
            if (!busy)
                log.BurnColor = null;
        }

        if (busy)
        {
            _cookEnd = cookEnd;
            _cookSeconds = cookSeconds;
            _cookStart = cookEnd - TimeSpan.FromSeconds(cookSeconds);
            StatusLabel.Text = Loc.GetString("medieval-campfire-menu-cooking");
        }
        else
        {
            // put the picked time back in place of the countdown
            SetCookTime(_selectedSeconds);
            StatusLabel.Text = empty
                ? Loc.GetString("medieval-campfire-menu-status-empty")
                : Loc.GetString("medieval-campfire-menu-status-ready");
        }
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        if (!_busy)
            return;

        // safety net in case the "done" state never arrives: don't leave the window locked
        if (_timing.CurTime > _cookEnd + TimeSpan.FromSeconds(2))
        {
            SetBusy(false, _empty, TimeSpan.Zero, 0);
            return;
        }

        var now = _timing.CurTime;
        var total = (_cookEnd - _cookStart).TotalSeconds;
        var progress = total <= 0 ? 1f : (float) Math.Clamp((now - _cookStart).TotalSeconds / total, 0, 1);

        var left = Math.Max(0, (int) Math.Ceiling((_cookEnd - now).TotalSeconds));
        TimeLabel.Text = Loc.GetString("medieval-campfire-menu-time-left", ("time", left));
        TimeLabel.FontColorOverride = TimeSetColor;

        BurnLogs(progress, (float) now.TotalSeconds);
    }

    /// <summary>
    ///     The chosen logs burn down from the right, one at a time: the one in the fire glows and flickers
    ///     and cools to ash as its share of the cook time runs out, the ones already burnt stay ash.
    /// </summary>
    private void BurnLogs(float progress, float time)
    {
        var count = (int) Math.Clamp(_cookSeconds / SecondsPerLog, 0, MaxLogs);
        if (count == 0)
            return;

        var burnt = progress * count;

        for (var i = 0; i < count; i++)
        {
            // rightmost log goes first
            var order = count - 1 - i;
            var log = _logs[i];

            if (burnt >= order + 1)
            {
                log.BurnColor = AshColor;
            }
            else if (burnt > order)
            {
                var flicker = 0.5f + 0.5f * MathF.Sin(time * EmberFlickerSpeed + i);
                var ember = Color.InterpolateBetween(EmberBright, EmberDeep, flicker);
                log.BurnColor = Color.InterpolateBetween(ember, AshColor, burnt - order);
            }
            else
            {
                // still waiting its turn: stays as a fresh log
                log.BurnColor = Color.White;
            }
        }
    }
}

/// <summary>
///     imperial medieval - one log of firewood under the campfire. Lit logs are the chosen cook time;
///     hover brightens whichever you point at.
/// </summary>
public sealed class CampfireLogButton : TextureButton
{
    private static readonly Color LitColor = Color.White;
    private static readonly Color LitHoverColor = Color.FromHex("#fff1c8");
    private static readonly Color UnlitColor = Color.FromHex("#4a4038");
    private static readonly Color UnlitHoverColor = Color.FromHex("#8a7a68");

    private bool _lit;
    private Color? _burnColor;

    public bool Lit
    {
        get => _lit;
        set
        {
            _lit = value;
            UpdateColor();
        }
    }

    /// <summary>Set while the log is burning in the fire, overrides the lit/unlit look.</summary>
    public Color? BurnColor
    {
        get => _burnColor;
        set
        {
            _burnColor = value;
            UpdateColor();
        }
    }

    public CampfireLogButton()
    {
        UpdateColor();
    }

    protected override void DrawModeChanged()
    {
        base.DrawModeChanged();
        UpdateColor();
    }

    private void UpdateColor()
    {
        if (_burnColor is { } burn)
        {
            ModulateSelfOverride = burn;
            return;
        }

        var hover = DrawMode == DrawModeEnum.Hover;
        ModulateSelfOverride = _lit
            ? hover ? LitHoverColor : LitColor
            : hover ? UnlitHoverColor : UnlitColor;
    }
}
