using System.Numerics;
using Content.Client.Imperial.Medieval.CapturePoint.UI.MedievalWindow;
using Content.Client.Imperial.Medieval.UserInterface.Elements;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;
using Robust.Shared.Utility;

namespace Content.Client.Imperial.Medieval.UserInterface.Windows;

/// <summary>
///     imperial medieval - campfire cooking window: the fire itself in the middle with the food laid out
///     around it, firewood for the cook time. Talks to the stock microwave logic through
///     <see cref="MedievalCampfireBoundUserInterface"/>.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class MedievalCampfireMenu : MedievalWindow
{
    [Dependency] private readonly IGameTiming _timing = default!;
    [Dependency] private readonly IEntityManager _entMan = default!;
    [Dependency] private readonly IResourceCache _resCache = default!;

    public const int MaxLogs = 6;
    public const uint SecondsPerLog = 5;

    // matches the stock microwave capacity the campfire uses
    private const int PotSlots = 10;

    // the server clears the busy flag a moment after cooking ends; past this the window unlocks on its own
    private static readonly TimeSpan UnlockGrace = TimeSpan.FromSeconds(2);

    private static readonly Vector2 PotSize = new(320, 300);
    private static readonly Vector2 RingCenter = new(160, 125);
    private static readonly Vector2 SlotSize = new(44, 44);
    private static readonly Vector2 SlotIconSize = new(32, 32);
    private static readonly Vector2 FireSize = new(96, 96);
    private static readonly Vector2 LogSize = new(40, 40);
    private const float LogGap = 4;
    private const float LogsTop = 252;
    private const float RingRadiusX = 120;
    private const float RingRadiusY = 95;

    private static readonly SpriteSpecifier LogSprite =
        new SpriteSpecifier.Rsi(new ResPath("/Textures/Objects/Specific/Hydroponics/towercap.rsi"), "produce");

    // burning firewood: glowing embers flicker between these, then the log cools down to ash
    private static readonly Color EmberBright = Color.FromHex("#ffc266");
    private static readonly Color EmberDeep = Color.FromHex("#ff6a1a");
    private static readonly Color AshColor = Color.FromHex("#2a2320");
    private const float EmberFlickerSpeed = 9f;

    /// <summary>Picked cook time in seconds, 0 = only warm up.</summary>
    public event Action<uint>? OnCookTimeSelected;

    public event Action<EntityUid>? OnIngredientPressed;

    private readonly SpriteView _fire;
    private readonly List<MedievalToggleButton> _slots = new();
    private readonly List<TextureRect> _slotIcons = new();
    private readonly EntityUid?[] _slotEntities = new EntityUid?[PotSlots];
    private readonly List<MedievalCampfireLogButton> _logs = new();

    private uint _selectedSeconds;

    private bool _busy;
    private bool _empty;
    private TimeSpan _cookStart;
    private TimeSpan _cookEnd;
    private int _burningLogs;

    public MedievalCampfireMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        TitleFont = MedievalUiStyle.TitleFont(_resCache);
        MedievalUiStyle.ApplyTextFont(_resCache, TimeLabel, StatusLabel, StartButton, EjectButton);

        PotLayout.SetSize = PotSize;

        _fire = new SpriteView
        {
            Scale = new Vector2(3, 3),
            SetSize = FireSize,
            MouseFilter = MouseFilterMode.Ignore,
        };
        Place(_fire, RingCenter - FireSize / 2, FireSize);

        BuildSlots();
        BuildLogs();
        ShowSelectedTime();
    }

    private void BuildSlots()
    {
        for (var i = 0; i < PotSlots; i++)
        {
            var index = i;
            var icon = new TextureRect
            {
                Stretch = TextureRect.StretchMode.KeepAspectCentered,
                SetSize = SlotIconSize,
                HorizontalAlignment = HAlignment.Center,
                VerticalAlignment = VAlignment.Center,
            };

            // never disabled, so empty slots keep the same look as full ones; clicks are filtered instead
            var slot = new MedievalToggleButton { SetSize = SlotSize };
            slot.AddChild(icon);
            slot.OnPressed += _ =>
            {
                if (!_busy && _slotEntities[index] is { } uid)
                    OnIngredientPressed?.Invoke(uid);
            };

            // a ring around the fire, starting from the top
            var angle = -MathF.PI / 2 + MathF.Tau * i / PotSlots;
            var offset = new Vector2(MathF.Cos(angle) * RingRadiusX, MathF.Sin(angle) * RingRadiusY);
            Place(slot, RingCenter + offset - SlotSize / 2, SlotSize);

            _slots.Add(slot);
            _slotIcons.Add(icon);
        }
    }

    private void BuildLogs()
    {
        var texture = _entMan.System<SpriteSystem>().Frame0(LogSprite);
        var rowWidth = MaxLogs * LogSize.X + (MaxLogs - 1) * LogGap;
        var x = (PotSize.X - rowWidth) / 2;

        for (var i = 1; i <= MaxLogs; i++)
        {
            var seconds = (uint) i * SecondsPerLog;
            var log = new MedievalCampfireLogButton
            {
                TextureNormal = texture,
                ToolTip = Loc.GetString("medieval-campfire-menu-seconds", ("time", seconds)),
            };
            log.OnPressed += _ => OnCookTimeSelected?.Invoke(seconds);

            Place(log, new Vector2(x, LogsTop), LogSize);
            x += LogSize.X + LogGap;
            _logs.Add(log);
        }
    }

    // fixed box in the pot layout via margins, so a slot never resizes to whatever icon it holds
    private void Place(Control control, Vector2 position, Vector2 size)
    {
        PotLayout.AddChild(control);
        LayoutContainer.SetMarginLeft(control, position.X);
        LayoutContainer.SetMarginTop(control, position.Y);
        LayoutContainer.SetMarginRight(control, position.X + size.X);
        LayoutContainer.SetMarginBottom(control, position.Y + size.Y);
    }

    private static int LogsFor(uint seconds)
    {
        return (int) Math.Min(seconds / SecondsPerLog, MaxLogs);
    }

    public void SetFire(EntityUid campfire)
    {
        _fire.SetEntity(campfire);
    }

    public void SetContents(IReadOnlyList<(EntityUid Uid, string Name, Texture? Icon)> contents)
    {
        for (var i = 0; i < PotSlots; i++)
        {
            var filled = i < contents.Count;

            _slotEntities[i] = filled ? contents[i].Uid : null;
            _slotIcons[i].Texture = filled ? contents[i].Icon : null;
            _slots[i].ToolTip = filled ? contents[i].Name : null;
        }
    }

    /// <summary>The picked cook time. While cooking it is only remembered and shown again once the fire is out.</summary>
    public void SetCookTime(uint seconds)
    {
        _selectedSeconds = seconds;

        if (!_busy)
            ShowSelectedTime();
    }

    public void SetBusy(bool busy, bool empty, TimeSpan cookEnd, uint cookSeconds)
    {
        _busy = busy;
        _empty = empty;

        StartButton.Disabled = busy || empty;
        EjectButton.Disabled = busy || empty;

        foreach (var log in _logs)
        {
            log.Disabled = busy;
        }

        if (busy)
        {
            _cookEnd = cookEnd;
            _cookStart = cookEnd - TimeSpan.FromSeconds(cookSeconds);
            _burningLogs = LogsFor(cookSeconds);
            StatusLabel.Text = Loc.GetString("medieval-campfire-menu-cooking");
            return;
        }

        foreach (var log in _logs)
        {
            log.BurnColor = null;
        }

        ShowSelectedTime();
        StatusLabel.Text = Loc.GetString(empty
            ? "medieval-campfire-menu-status-empty"
            : "medieval-campfire-menu-status-ready");
    }

    private void ShowSelectedTime()
    {
        var lit = LogsFor(_selectedSeconds);

        for (var i = 0; i < _logs.Count; i++)
        {
            _logs[i].Lit = i < lit;
        }

        if (lit == 0)
        {
            TimeLabel.Text = Loc.GetString("medieval-campfire-menu-time-none");
            TimeLabel.FontColorOverride = MedievalUiStyle.Text;
            StartButton.ToolTip = Loc.GetString("medieval-campfire-menu-time-warm");
        }
        else
        {
            TimeLabel.Text = Loc.GetString("medieval-campfire-menu-time", ("time", _selectedSeconds));
            TimeLabel.FontColorOverride = MedievalUiStyle.Gold;
            StartButton.ToolTip = null;
        }
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        if (!_busy)
            return;

        var now = _timing.CurTime;

        // don't leave the window locked if the "done" state never arrives
        if (now > _cookEnd + UnlockGrace)
        {
            SetBusy(false, _empty, TimeSpan.Zero, 0);
            return;
        }

        var left = Math.Max(0, (int) Math.Ceiling((_cookEnd - now).TotalSeconds));
        TimeLabel.Text = Loc.GetString("medieval-campfire-menu-time-left", ("time", left));
        TimeLabel.FontColorOverride = MedievalUiStyle.Gold;

        var total = (_cookEnd - _cookStart).TotalSeconds;
        var progress = total <= 0 ? 1f : (float) Math.Clamp((now - _cookStart).TotalSeconds / total, 0, 1);
        BurnLogs(progress, (float) now.TotalSeconds);
    }

    /// <summary>
    ///     The chosen logs burn down from the right, one at a time: the one in the fire glows and flickers
    ///     and cools to ash as its share of the cook time runs out, the ones already burnt stay ash.
    /// </summary>
    private void BurnLogs(float progress, float time)
    {
        var burnt = progress * _burningLogs;

        for (var i = 0; i < _burningLogs; i++)
        {
            // rightmost log goes first
            var turn = _burningLogs - 1 - i;

            if (burnt >= turn + 1)
            {
                _logs[i].BurnColor = AshColor;
            }
            else if (burnt > turn)
            {
                var flicker = 0.5f + 0.5f * MathF.Sin(time * EmberFlickerSpeed + i);
                var ember = Color.InterpolateBetween(EmberBright, EmberDeep, flicker);
                _logs[i].BurnColor = Color.InterpolateBetween(ember, AshColor, burnt - turn);
            }
            else
            {
                // still waiting its turn
                _logs[i].BurnColor = Color.White;
            }
        }
    }
}
